const mongoose = require('mongoose');

/**
 * @file server/models/Product.js
 * @description Defines the Mongoose schema and model for a Product.
 * This model represents a single product in the e-commerce catalog,
 * including its details, pricing, inventory, images, and user ratings.
 */

const productSchema = new mongoose.Schema({
    /**
     * The name of the product.
     * Must be unique, required, trimmed, and at least 3 characters long.
     */
    name: {
        type: String,
        required: [true, 'Product name is required'],
        trim: true,
        unique: true, // Ensures product names are unique
        minlength: [3, 'Product name must be at least 3 characters long']
    },
    /**
     * A detailed description of the product.
     * Required, trimmed, and at least 10 characters long.
     */
    description: {
        type: String,
        required: [true, 'Product description is required'],
        trim: true,
        minlength: [10, 'Product description must be at least 10 characters long']
    },
    /**
     * The price of the product.
     * Required and must be a non-negative number.
     */
    price: {
        type: Number,
        required: [true, 'Product price is required'],
        min: [0, 'Price cannot be negative']
    },
    /**
     * The category the product belongs to (e.g., "Electronics", "Apparel").
     * Required and trimmed.
     */
    category: {
        type: String,
        required: [true, 'Product category is required'],
        trim: true,
        // In a more advanced setup, this could be an enum or reference a Category model
    },
    /**
     * The brand of the product.
     * Optional and trimmed.
     */
    brand: {
        type: String,
        trim: true
    },
    /**
     * Stock Keeping Unit (SKU) - a unique identifier for inventory management.
     * Required, unique, and trimmed.
     */
    sku: {
        type: String,
        required: [true, 'SKU is required'],
        unique: true,
        trim: true
    },
    /**
     * An array of URLs pointing to product images.
     * Defaults to an empty array if no images are provided.
     */
    images: [
        {
            type: String,
            trim: true
        }
    ],
    /**
     * The current quantity of the product available in stock.
     * Required, must be non-negative, and defaults to 0.
     */
    stockQuantity: {
        type: Number,
        required: [true, 'Stock quantity is required'],
        min: [0, 'Stock quantity cannot be negative'],
        default: 0
    },
    /**
     * A boolean flag indicating if the product should be featured on the homepage or special sections.
     * Defaults to false.
     */
    isFeatured: {
        type: Boolean,
        default: false
    },
    /**
     * An array of user ratings and reviews for the product.
     * Each rating includes the user who submitted it, the rating value (1-5),
     * an optional comment, and the timestamp of the review.
     */
    ratings: [
        {
            userId: {
                type: mongoose.Schema.Types.ObjectId,
                ref: 'User', // References a 'User' model (assuming user authentication is implemented)
                required: true
            },
            rating: {
                type: Number,
                min: [1, 'Rating must be at least 1'],
                max: [5, 'Rating cannot be more than 5'],
                required: true
            },
            comment: {
                type: String,
                trim: true
            },
            createdAt: {
                type: Date,
                default: Date.now
            }
        }
    ],
    /**
     * The total count of reviews for the product.
     * This field is automatically updated via a pre-save hook for efficiency.
     */
    reviewsCount: {
        type: Number,
        default: 0
    },
    // --- Cross-Project Context Mentions (Optional fields for microservice integration) ---
    /**
     * Optional: A short URL for this product, potentially generated by a URL Shortener service.
     * This could be used for sharing product links more concisely.
     * shortUrl: {
     *     type: String,
     *     trim: true,
     *     unique: true,
     *     sparse: true // Allows multiple documents to have null/undefined shortUrl
     * },
     */
    /**
     * Optional: A description generated or enhanced by an AI-Powered Content Assistant.
     * This could provide richer, more engaging product descriptions.
     * aiGeneratedDescription: {
     *     type: String,
     *     trim: true
     * }
     */
}, {
    timestamps: true, // Automatically adds `createdAt` and `updatedAt` fields
    toJSON: { virtuals: true }, // Ensures virtual properties are included when converting to JSON
    toObject: { virtuals: true } // Ensures virtual properties are included when converting to object
});

/**
 * Virtual property: `averageRating`
 * Calculates the average rating of the product based on its `ratings` array.
 * Returns the average to one decimal place, or 0 if no ratings exist.
 */
productSchema.virtual('averageRating').get(function() {
    if (this.ratings && this.ratings.length > 0) {
        const totalRating = this.ratings.reduce((acc, item) => item.rating + acc, 0);
        return parseFloat((totalRating / this.ratings.length).toFixed(1));
    }
    return 0;
});

/**
 * Pre-save hook: Updates `reviewsCount` before saving the document.
 * This ensures `reviewsCount` is always consistent with the number of ratings.
 */
productSchema.pre('save', function(next) {
    // Only update if the 'ratings' array has been modified
    if (this.isModified('ratings')) {
        this.reviewsCount = this.ratings.length;
    }
    next();
});

/**
 * Mongoose Indexes for improved query performance.
 *
 * - Text index on `name`, `description`, `category`, `brand` for full-text search.
 * - Single field indexes for common filtering and sorting operations.
 */
productSchema.index({ name: 'text', description: 'text', category: 'text', brand: 'text' });
productSchema.index({ price: 1 }); // For sorting by price (ascending)
productSchema.index({ category: 1 }); // For filtering by category
productSchema.index({ brand: 1 }); // For filtering by brand
productSchema.index({ stockQuantity: 1 }); // For filtering by stock availability
productSchema.index({ reviewsCount: -1 }); // For sorting by number of reviews (descending)

// Note: An index on `averageRating` virtual property is not directly possible.
// If sorting/filtering by average rating is critical for large datasets,
// consider storing `averageRating` as a regular field and updating it
// in a pre-save hook or a separate service when ratings change.

/**
 * Create the Mongoose model for 'Product' using the defined schema.
 */
const Product = mongoose.model('Product', productSchema);

module.exports = Product;